// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_K84bohXIOlrNVwgmOV5HFSkD7mUw70',
    appId: '1:856370151794:web:075d60a0f25bdb4acb5deb',
    messagingSenderId: '856370151794',
    projectId: 'pucon2025-bb8f0',
    authDomain: 'pucon2025-bb8f0.firebaseapp.com',
    storageBucket: 'pucon2025-bb8f0.firebasestorage.app',
    measurementId: 'G-PWECZVSWYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCesQVKeowkMwWPA-zt3p5V3i5ikHmk_9A',
    appId: '1:856370151794:android:f7f779566f065f4dcb5deb',
    messagingSenderId: '856370151794',
    projectId: 'pucon2025-bb8f0',
    storageBucket: 'pucon2025-bb8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjwhKeZuSnKltadbSnmjk31iWe4bZG8U',
    appId: '1:856370151794:ios:e8382f789ba4431ecb5deb',
    messagingSenderId: '856370151794',
    projectId: 'pucon2025-bb8f0',
    storageBucket: 'pucon2025-bb8f0.firebasestorage.app',
    iosBundleId: 'com.hansoft.pucon2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjwhKeZuSnKltadbSnmjk31iWe4bZG8U',
    appId: '1:856370151794:ios:4385b9bcc67b66d6cb5deb',
    messagingSenderId: '856370151794',
    projectId: 'pucon2025-bb8f0',
    storageBucket: 'pucon2025-bb8f0.firebasestorage.app',
    iosBundleId: 'com.example.stackedpractice01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf_K84bohXIOlrNVwgmOV5HFSkD7mUw70',
    appId: '1:856370151794:web:1928b17b244dc14fcb5deb',
    messagingSenderId: '856370151794',
    projectId: 'pucon2025-bb8f0',
    authDomain: 'pucon2025-bb8f0.firebaseapp.com',
    storageBucket: 'pucon2025-bb8f0.firebasestorage.app',
    measurementId: 'G-0ECYRGBZZ4',
  );
}
